/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.awt.Font;


/**
 *
 * @author henri
 */
public class telaGenio extends javax.swing.JFrame {
     private int tentativasRestantes;
     double valorGeradoDouble;
     int valorGeradoInt;
    /**
     * Creates new form telaGenio
     */
    public telaGenio() {
        initComponents();
           
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTentativas = new javax.swing.JLabel();
        btnReniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 179, -1));

        lblFrase.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Frase");
        lblFrase.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 160, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao_de_fala.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 30));

        txtValor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 50, 30));

        btnPalpite.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tentativas Restantes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 180, 20));

        lblTentativas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTentativas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTentativas.setText("num");
        getContentPane().add(lblTentativas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, 20));

        btnReniciar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnReniciar.setText("Reniciar");
        btnReniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        int numPalpite = Integer.parseInt(txtValor.getValue().toString());
       
        String frase1 = "<html>Acertou! Clique em Reniciar para começar de novo</html>";
        String frase2 = "<html>ERROU! Pensei um numero maior. Tente Novamente!</html>";
        String frase3 = "<html>ERROU! Pensei um numero menor. Tente Novamente!</html>";
        String frase4 = "<html>Você perdeu! Suas tentativas acabaram. Eu pensei no número " + valorGeradoInt + ".</html>";
       
        if(tentativasRestantes > 0) {
            if(valorGeradoInt == numPalpite){
               lblFrase.setFont(new Font("Arial Black", Font.PLAIN, 16));   
               lblFrase.setText(frase1);
            } else {
                tentativasRestantes--;
                lblTentativas.setText(Integer.toString(tentativasRestantes));
                if(tentativasRestantes == 0) {
                    lblFrase.setFont(new Font("Arial Black", Font.PLAIN, 16));
                    lblFrase.setText(frase4);
                } else if(valorGeradoInt > numPalpite){
                    lblFrase.setFont(new Font("Arial Black", Font.PLAIN, 16));
                    lblFrase.setText(frase2);
                } else {
                    lblFrase.setFont(new Font("Arial Black", Font.PLAIN, 16));
                    lblFrase.setText(frase3);                 
                }
            }
        }
    }//GEN-LAST:event_btnPalpiteActionPerformed

    private void btnReniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReniciarActionPerformed
        
    }//GEN-LAST:event_btnReniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JButton btnReniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblTentativas;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables
}
